services:
  edge-ai:
    build: .
    network_mode: host
    privileged: true
    restart: unless-stopped

    environment:
      - PYTHONUNBUFFERED=1

    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyACM0:/dev/ttyACM0

    volumes:
      - ./logs:/app/logs
      - ./models:/app/models